[features]
seeds = false
skip-lint = false
[programs.localnet]
game = "8j87roQKzuTLhz7n4dvbX5GeMuYuBEnWDECgNyRYmmzQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/atreides/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
