[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "CR5DnpzdCjRv6rYT9ocxkxmJJsMesuZPvj14kNa7MfaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tadeo/gitlab/solana/keys/local-tam.json"

[scripts]
test = "node tests/myepicproject.js"


