[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "3MbNLMpDptCDdbr4eWKwjvsmQA3mJjcwHczcBLoWtwrM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/atreides/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"


