[features]
seeds = false
skip-lint = false
[programs.localnet]
flipper = "H4NKh3j5pZZsnFjRa7NskaZrxkWvXv4PvfbYJDPYaLUP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/atreides/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
