[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet = "Cz6mSFHjPQqK7A5YHY3gNNdJY2Nbawye8BHF8P74AbND"
puppet_master = "FTThqJq6mBT9j8itTXemvkWjSB21JGgW6ERGLofNBqk3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/atreides/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
