[features]
seeds = false
[programs.localnet]
cpipda = "ACZZdHNuhnvbrjE3DRVGdqg7X2NzKJAYGiEAd5bpA1sv"
proxy = "3GhBo6kSG4519BGNj346DLS6S427UBvq1hfSctTA6qzx"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/tadeo/gitlab/solana/keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
